### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by viceice** [istanbuljs/v8-to-istanbul#134]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `v8-to-istanbul@7.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js b/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js
index 428c02a..e5be920 100644
--- a/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js
+++ b/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js
@@ -54,7 +54,7 @@ module.exports = class V8ToIstanbul {
         this.sourceTranspiled = new CovSource(rawSource, this.wrapperLength)
       } else {
         const candidatePath = this.rawSourceMap.sourcemap.sources.length >= 1 ? this.rawSourceMap.sourcemap.sources[0] : this.rawSourceMap.sourcemap.file
-        this.path = this._resolveSource(this.rawSourceMap, candidatePath)
+        this.path = this._resolveSource(this.rawSourceMap, candidatePath || this.path)
         this.sourceMap = await new SourceMapConsumer(this.rawSourceMap.sourcemap)
 
         let originalRawSource
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by viceice** [comment]
```
TypeError: Cannot read property 'replace' of undefined
    at V8ToIstanbul._resolveSource (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:86:29)
    at V8ToIstanbul.load (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:57:26)
    at C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\reporters\build\CoverageReporter.js:624:27
    at Array.map (<anonymous>)
    at CoverageReporter._getCoverageResult (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\reporters\build\CoverageReporter.js:587:32)
    at CoverageReporter.onRunComplete (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\reporters\build\CoverageReporter.js:231:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ReporterDispatcher.onRunComplete (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\core\build\ReporterDispatcher.js:88:9)
    at async TestScheduler.scheduleTests (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\core\build\TestScheduler.js:350:5)
    at async runJest (C:\Users\kriese\projects\gh\renovatebot\renovate\node_modules\@jest\core\build\runJest.js:376:19)
```
