### ISSUE TITLE
An error occurred while trying to read the map file

### ISSUE THREAD

**Issue by eliw00d** [istanbuljs/v8-to-istanbul#197]
I'm trying to get this to work with Playwright + Electron and have the following:

```
test.beforeAll(async () => {
    page = await electronApp.firstWindow()
    await page.coverage.startJSCoverage()
})

test.afterAll(async () => {
    const coverage = await page.coverage.stopJSCoverage()
    for (const entry of coverage) {
      const converter = v8toIstanbul('', 0, { source: entry.source! })
      await converter.load()
      converter.applyCoverage(entry.functions)
      console.log(JSON.stringify(converter.toIstanbul()))
    }
})
```

It works for one test but another throws the following error:

```
Error: An error occurred while trying to read the map file at /Users/eliw00d/projects/myProject/index.js.map
Error: ENOENT: no such file or directory, open '/Users/eliw00d/projects/myProject/index.js.map'
    at readFromFileMap (/Users/eliw00d/projects/myProject/node_modules/convert-source-map/index.js:40:11)
    at new Converter (/Users/eliw00d/projects/myProject/node_modules/convert-source-map/index.js:47:32)
    at Object.exports.fromMapFileComment (/Users/eliw00d/projects/myProject/node_modules/convert-source-map/index.js:110:10)
    at Object.exports.fromMapFileSource (/Users/eliw00d/projects/myProject/node_modules/convert-source-map/index.js:122:22)
    at V8ToIstanbul.load (/Users/eliw00d/projects/myProject/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:52:66)
    at TestInfoImpl._runAsStep (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/testInfo.js:201:22)
    at /Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/workerRunner.js:655:9
    at TestInfoImpl._runFn (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/testInfo.js:166:7)
    at WorkerRunner._runAfterAllHooksForSuite (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/workerRunner.js:642:29)
    at /Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/workerRunner.js:499:33
    at TimeoutRunner.run (/Users/eliw00d/projects/myProject/node_modules/playwright-core/lib/utils/timeoutRunner.js:53:14)
    at TimeoutManager.runWithTimeout (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/timeoutManager.js:73:7)
    at TestInfoImpl._runWithTimeout (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/testInfo.js:154:26)
    at WorkerRunner._runTest (/Users/eliw00d/projects/myProject/node_modules/@playwright/test/lib/workerRunner.js:464:5)
```

Which points to: https://github.com/istanbuljs/v8-to-istanbul/blob/master/lib/v8-to-istanbul.js#L52

I have `"sourceMap": true` in my tsconfig.json so I'm not sure what's going on here. Any thoughts?

**Comment by testgitdl** [comment]
I have the same problem. Any idea on how to solve? Thanks!
